- name: MySQL Setup
  hosts: mysql
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Install MySQL Server
      ansible.builtin.apt:
        name: mysql-server
        state: latest
        update_cache: yes

    - name: Install pip3
      ansible.builtin.apt:
        name: python3-pip
        state: latest    

    - name: Install Python MySQL Client
      ansible.builtin.pip:
        name:
          - PyMySQL
          - cryptography
        executable: pip3    

    - name: Start MySQL Service
      ansible.builtin.systemd:
        name: mysql
        state: started    
        enabled: yes   

    - name: Configure MySQL to listen on all IP addresses
      ansible.builtin.lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'
        state: present

    - name: Restart MySQL Service to apply changes
      ansible.builtin.systemd:
        name: mysql
        state: restarted

    - name: Set MySQL root password
      community.mysql.mysql_user:
        name: root
        host: localhost
        password: 'ExpenseApp@1'
        state: present    

    # - name: Flush MySQL privileges
    #   ansible.builtin.shell: |
    #     mysql -e "FLUSH PRIVILEGES;"
    #   args:
    #     executable: /bin/bash 

    # - name: Alter MySQL root user password
    #   ansible.builtin.shell: |
    #     mysql -e "ALTER USER 'root'@'%' IDENTIFIED WITH caching_sha2_password BY 'ExpenseApp@1';"
    #   args:
    #     executable: /bin/bash        

    # - name: Set MySQL root password if not set
    #   community.mysql.mysql_user:
    #     name: root
    #     host: 172.31.27.148
    #     password: 'ExpenseApp@1'
    #     state: present    

    # - name: Flush MySQL privileges
    #   community.mysql.mysql_db:
    #     login_user: root
    #     login_password: ExpenseApp@1
    #     login_host: 172.31.27.148
    #     state: present
    #     name: ''
    #     sql: 'FLUSH PRIVILEGES;'

    # - name: Alter MySQL root user password
    #   community.mysql.mysql_user:
    #     name: 'root'
    #     host: '%'
    #     password: 'ExpenseApp@1'
    #     plugin: caching_sha2_password
    #     state: present

    - name: Create expense user
      community.mysql.mysql_user:
        name: 'expense'
        host: '%'
        password: 'ExpenseApp@1'
        state: present
